name: map_sample
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.1.2
  geolocator: ^8.2.0
  firebase_core: ^1.13.1
  cloud_firestore: ^3.1.10
  geoflutterfire: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
flutter:
  uses-material-design: true